version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-frontend
      - app-backend
    ports:
      - 3000:80
    container_name: nginx
  app-frontend:
    image: todo-front
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=/api/
    container_name: todo-front
  app-backend:
    image: todo-back
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    container_name: todo-back
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis-server
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongo-server

